name: release
on:
  push:
    branches:
    - docs

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Sphinx
    - name: Build sphinx documentation
      run: |
        cd docs
        make clean
        make html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.0.4
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: docs # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/build/html # The folder the action should deploy.: